name: Containers

on:
  push:
    paths:
    - '.github/*.dockerfile'
    - '.github/workflows/Containers.yml'
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:

  Container:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
        - impl
        - sim
    name: '🛳️ ${{ matrix.image }}'

    steps:

    - name: '🧰 Repository Checkout'
      uses: actions/checkout@v5

    - name: '⛴️ Build neorv32/${{ matrix.image }}'
      run: docker build -t ghcr.io/stnolting/neorv32/${{ matrix.image }} - < .github/${{ matrix.image }}.dockerfile

    - name: '🔑 Login to ghcr.io'
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: gha
        password: ${{ secrets.PACKAGE_TOKEN }}

    - name: '🛰️ Push image to ghcr.io'
      run: docker push ghcr.io/stnolting/neorv32/${{ matrix.image }}
